### ISSUE TITLE
When creating a new vm with a static ip the portmap gets created with the wrong ip.

### ISSUE THREAD

**Issue by eagled2** [willnx/vlab_winserver#12]
I ran into an issue where creating a windows VM in vlab using a static ip doesn't allow connection to rdp through the 'vlab connect' command. This appears to be happening because the portmap is created incorrectly when setting a static ip. 
What I found is that the portmap is created using what I assume is the initial dynamically assigned ip the vm was using before it set the static ip. Work around is pretty simple, delete/create portmap, but it should work upon install.

Steps to repro;
From vlab i created a new windows 2019 vm using a static ip.
PS C:\Users\myuser> vlab -o create winserver -i 2019 -n win2019 -s 192.168.1.19
Creating a new instance of Microsoft Server 2019
Creating an RDP port mapping rule
Type      :  WinServer
Version   :  2019
State     :  poweredOn
IPs       :  192.168.1.151
Networks  :  frontend
You can see here that the portmap was created using the ip listed during creation which doesn't match the static ip I selected.
PS C:\Users\myuser> vlab -o show portmap -v |Select-String win2019
 win2019  | WinServer | 50067  | RDP        | 192.168.1.151
connecting to this vm through console I was able confirm that the ip assigned is in fact the static ip I selected, but I couldn't get output from the vm so here is a screenshot.
![vlab-ad](https://user-images.githubusercontent.com/51394569/141206557-6690c68f-8ce2-4831-abaa-9bfce3f99fb3.JPG)

**Comment by willnx** [comment]
I'm sorry, but I do not actively support vLab anymore. Please contact your local developer/maintainer, or submit a PR that would fix the issue.
